<?php

namespace backend\controllers;

use common\components\AutoTable;
use Yii;

class TableController extends BaseController {
    protected $tableName = '';
    protected $autoTable = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->tableName = $this->request->get('table');
        $this->autoTable = AutoTable::getInstance($this->tableName);

        //$this->config =
    }


    public function actionList(){
        $this->displayHtml('list',[
            'name' => $this->tableName,
            'config' => $this->autoTable->getConfig(),
        ]);
    }

    public function actionListData(){
        //$this->autoTable->getListData();
        $this->displayData([]);
    }

}
